backend:
  name: github
  repo: hamadhadi116/khotwa-website
  branch: main
  auth_type: implicit

media_folder: "assets/img"
public_folder: "/assets/img"

locale: ar

collections:
  # ملف إعدادات ثابت (file collection)
  - label: "Settings"
    name: "settings"
    files:
      - label: "Site Settings"
        name: "site"
        file: "assets/data/settings.json"
        format: "json"
        fields:
          - { label: "Site Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }

  # أحداث: ملف JSON واحد فيه قائمة items (file collection صحيحة)
  - label: "Events"
    name: "events"
    files:
      - label: "Events Data"
        name: "events_data"
        file: "assets/data/events.json"
        format: "json"
        fields:
          - label: "Events"
            name: "items"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Date", name: "date", widget: "datetime" }
              - { label: "Location", name: "location", widget: "string" }
              - { label: "Summary", name: "summary", widget: "text" }

  # أخبار: ملف JSON واحد فيه قائمة items (file collection صحيحة)
  - label: "News"
    name: "news"
    files:
      - label: "News Data"
        name: "news_data"
        file: "assets/data/news.json"
        format: "json"
        fields:
          - label: "Articles"
            name: "items"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Date", name: "date", widget: "datetime" }
              - { label: "Body", name: "body", widget: "markdown" }
